version: "3.5"
services:
  app:
    image: ghcr.io/suecharo/gh-trs:1.1.14
    container_name: gh-trs
    volumes:
      - ${PWD}/.env:/app/.env
      - ${PWD}/sapporo_run:/app/sapporo_run
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SAPPORO_RUN_DIR=${PWD}/run
    restart: on-failure
    working_dir: /app
    command: [ "sleep", "infinity" ]
    networks:
      - gh-trs-network

networks:
  gh-trs-network:
    name: gh-trs-network
